import { CharacterProfile, Quest, ShopItem } from '../../types';

export const INITIAL_PROFILE: CharacterProfile = {
  id: 'guest_hero_1',
  username: 'Alex the Ascendant',
  title: 'Novice Adventurer',
  level: 1,
  xp: 35,
  gold: 75,
  streak: 3,
  last_active_date: new Date().toISOString().split('T')[0],
  stats: {
    strength: 12,
    intellect: 15,
    charisma: 11,
    creativity: 14,
  },
  equipped_theme: 'dark_fantasy',
  equipped_badge: 'Novice',
};

export const SEED_QUESTS: Quest[] = [
  {
    id: 'seed-quest-1',
    title: 'Complete strength training',
    description: 'Hit the gym or complete full-body resistance circuit.',
    attribute: 'Strength',
    difficulty: 'Medium',
    xp_reward: 35,
    gold_reward: 25,
    completed: false,
    streak_count: 2,
    is_daily: true,
  },
  {
    id: 'seed-quest-2',
    title: '1 hour of React coding',
    description: 'Deep work session crafting components and state flows.',
    attribute: 'Intellect',
    difficulty: 'Hard',
    xp_reward: 50,
    gold_reward: 40,
    completed: false,
    streak_count: 5,
    is_daily: true,
  },
  {
    id: 'seed-quest-3',
    title: 'English conversation practice',
    description: 'Engage in fluid dialogue to sharpen vocal articulation.',
    attribute: 'Charisma',
    difficulty: 'Medium',
    xp_reward: 30,
    gold_reward: 20,
    completed: false,
    streak_count: 1,
    is_daily: true,
  },
  {
    id: 'seed-quest-4',
    title: 'Practice acoustic guitar',
    description: 'Fingerstyle rhythm drills and chord transition mastery.',
    attribute: 'Creativity',
    difficulty: 'Easy',
    xp_reward: 25,
    gold_reward: 15,
    completed: false,
    streak_count: 3,
    is_daily: true,
  },
];

export const SHOP_ITEMS: ShopItem[] = [
  {
    id: 'item_xp_potion_small',
    name: 'Elixir of Clarity',
    description: 'Instant rush of mental clarity. Grants +50 XP immediately.',
    category: 'potion',
    cost: 30,
    icon: 'FlaskConical',
    stat_boost: { xp: 50 },
    rarity: 'Common',
  },
  {
    id: 'item_streak_shield',
    name: 'Aegis of Continuity',
    description: 'Protects your streak counter from breaking if you miss a day.',
    category: 'potion',
    cost: 80,
    icon: 'Shield',
    stat_boost: { streak_freeze: 1 },
    rarity: 'Rare',
  },
  {
    id: 'item_iron_dumbbell',
    name: 'Gauntlets of Iron Will',
    description: 'Hardens resolve and muscle stamina. +5 Strength permanently.',
    category: 'equipment',
    cost: 120,
    icon: 'Dumbbell',
    stat_boost: { strength: 5 },
    rarity: 'Rare',
  },
  {
    id: 'item_crystal_codex',
    name: 'Tome of Clean Architecture',
    description: 'Enhances cognitive pattern recognition. +5 Intellect permanently.',
    category: 'equipment',
    cost: 120,
    icon: 'BookOpen',
    stat_boost: { intellect: 5 },
    rarity: 'Rare',
  },
  {
    id: 'title_syntax_knight',
    name: 'Title: Syntax Knight',
    description: 'Showcases your algorithmic discipline on your Hero Card.',
    category: 'title',
    cost: 50,
    icon: 'Crown',
    rarity: 'Common',
  },
  {
    id: 'theme_cyberpunk',
    name: 'Theme: Neon Cyberpunk',
    description: 'Infuses your HUD with high-contrast cyan and neon accents.',
    category: 'theme',
    cost: 150,
    icon: 'Palette',
    rarity: 'Epic',
  },
];
